// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itemexvbnbmbqbizpoxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZW1leHZibmJtYnFiaXpwb3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODEzMzcsImV4cCI6MjA2NTQ1NzMzN30.0eJHhVkgAwsGtLC9cCs2paaawRERsPAG65ehFvjg6FA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});